# Stage 1: Install dependencies and build
FROM node:24-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
ARG NEXT_PUBLIC_BASE_URL
ARG MONGO_URI
ARG AUTH_SECRET
ARG RESEND_KEY
ARG GOOGLE_ID
ARG GOOGLE_SECRET

ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV MONGO_URI=$MONGO_URI
ENV AUTH_SECRET=$AUTH_SECRET
ENV RESEND_KEY=$RESEND_KEY
ENV GOOGLE_ID=$GOOGLE_ID
ENV GOOGLE_SECRET=$GOOGLE_SECRET
RUN npm run build


FROM node:24-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app ./
EXPOSE 3000
CMD ["npm", "run", "start"]