name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        env:
          NEXT_PUBLIC_BASE_URL: https://todo.jgengo.fr
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL} \
            --build-arg MONGO_URI=${MONGO_URI} \
            -t ghcr.io/${{ github.repository_owner }}/todo:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/todo:latest
